//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        public PRODUCTOS()
        {
            this.PEDIDOS = new HashSet<PEDIDOS>();
        }
    
        public int PRO_CONT { get; set; }
        public Nullable<int> COM_CONT { get; set; }
        public string PRO_PRIMA { get; set; }
        public string PRO_COBERTURA { get; set; }
        public string PRO_ASISTENCIA { get; set; }
        public string PRO_NOMBRE { get; set; }
    
        public virtual COMPANIA COMPANIA { get; set; }
        public virtual ICollection<PEDIDOS> PEDIDOS { get; set; }
    }
}
